//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hound.Bot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hound.Bot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :no_entry_sign: Цвет {0} для роли **{1}** был добавлен ранее..
        /// </summary>
        internal static string ColorAddExist {
            get {
                return ResourceManager.GetString("ColorAddExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указана роль и-или цвет.
        ///Формат: !добавить @Role #fcba03.
        /// </summary>
        internal static string ColorAddParametersIsNull {
            get {
                return ResourceManager.GetString("ColorAddParametersIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :floppy_disk: Для роли **{0}**, сохранен цвет #{1}..
        /// </summary>
        internal static string ColorAddSuccess {
            get {
                return ResourceManager.GetString("ColorAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :no_entry_sign: Миша все хуйня, давай по новой.(Некоректный формат цвета).
        /// </summary>
        internal static string ColorAddWrongFormat {
            get {
                return ResourceManager.GetString("ColorAddWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для проверки цвета используй - https://www.color-hex.com/.
        /// </summary>
        internal static string ColorListEmbedFooterText {
            get {
                return ResourceManager.GetString("ColorListEmbedFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки цветов для ролей.
        /// </summary>
        internal static string ColorListEmbedTitle {
            get {
                return ResourceManager.GetString("ColorListEmbedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :no_entry_sign: Не сохранено ни одной роли..
        /// </summary>
        internal static string ColorListEmpty {
            get {
                return ResourceManager.GetString("ColorListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки цветов для роли {0}.
        /// </summary>
        internal static string ColorListRoleFieldTitle {
            get {
                return ResourceManager.GetString("ColorListRoleFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово. Я разослал сообщением всем у кого есть роль **{0}**.
        ///- Всего получателей: **{1}**
        ///- Успешно доставлено: **{2}**
        ///- Не удалось отправить: **{3}**.
        /// </summary>
        internal static string DoneMailing {
            get {
                return ResourceManager.GetString("DoneMailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :mailbox_with_mail: Вам сообщение от {0} с сервера **`{1}`**.
        /// </summary>
        internal static string MailEmbedTitle {
            get {
                return ResourceManager.GetString("MailEmbedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приступаю к рассылке {0} сообщений. Всем пользователям с ролью **{1}**..
        /// </summary>
        internal static string StartMailing {
            get {
                return ResourceManager.GetString("StartMailing", resourceCulture);
            }
        }
    }
}
